// Date: 7/24/2014 8:14:58 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fantastic.renders.models.armor;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDiverPants extends ModelBiped
{
  //fields
    ModelRenderer pantsbottom;
    ModelRenderer pantstop;
    ModelRenderer pantsfront;
    ModelRenderer legR;
    ModelRenderer lowerlegR;
    ModelRenderer upperlegR;
    ModelRenderer kneejointR;
    ModelRenderer legL;
    ModelRenderer lowerlegL;
    ModelRenderer upperlegL;
    ModelRenderer kneejointL;
  
  public ModelDiverPants(float f)
  {
	  super(f, 0, 64, 128);
    textureWidth = 64;
    textureHeight = 128;
    
      pantsbottom = new ModelRenderer(this, 0, 62);
      pantsbottom.addBox(-4F, 11F, -2F, 8, 1, 4);
      pantsbottom.setRotationPoint(0F, 0F, 0F);
      pantsbottom.setTextureSize(64, 128);
      pantsbottom.mirror = true;
      setRotation(pantsbottom, 0F, 0F, 0F);
      pantstop = new ModelRenderer(this, 0, 55);
      pantstop.addBox(-4.5F, 9F, -2.5F, 9, 2, 5, f);
      pantstop.setRotationPoint(0F, 0F, 0F);
      pantstop.setTextureSize(64, 128);
      pantstop.mirror = true;
      setRotation(pantstop, 0F, 0F, 0F);
      pantsfront = new ModelRenderer(this, 16, 67);
      pantsfront.addBox(-1.5F, 8.5F, -3F, 3, 3, 1);
      pantsfront.setRotationPoint(0F, 0F, 0F);
      pantsfront.setTextureSize(64, 128);
      pantsfront.mirror = true;
      setRotation(pantsfront, 0F, 0F, 0F);
      legR = new ModelRenderer(this, 0, 67);
      legR.addBox(-2F, 0F, -2F, 4, 8, 4, f);
      legR.setRotationPoint(0F, 0F, 0F);
      legR.setTextureSize(64, 128);
      legR.mirror = true;
      setRotation(legR, 0F, 0F, 0F);
      lowerlegR = new ModelRenderer(this, 0, 88);
      lowerlegR.mirror = true;
      lowerlegR.addBox(-2.5F, 4F, -2.5F, 3, 3, 5, f);
      lowerlegR.setRotationPoint(0F, 0F, 0F);
      lowerlegR.setTextureSize(64, 128);
      lowerlegR.mirror = true;
      setRotation(lowerlegR, 0F, 0F, 0F);
      lowerlegR.mirror = false;
      upperlegR = new ModelRenderer(this, 0, 79);
      upperlegR.mirror = true;
      upperlegR.addBox(-3F, -0.5F, -2.5F, 4, 4, 5, f);
      upperlegR.setRotationPoint(0F, 0F, 0F);
      upperlegR.setTextureSize(64, 128);
      upperlegR.mirror = true;
      setRotation(upperlegR, 0F, 0F, 0F);
      upperlegR.mirror = false;
      kneejointR = new ModelRenderer(this, 13, 79);
      kneejointR.mirror = true;
      kneejointR.addBox(-3.5F, 3F, -1F, 2, 2, 2);
      kneejointR.setRotationPoint(0F, 0F, 0F);
      kneejointR.setTextureSize(64, 128);
      kneejointR.mirror = true;
      setRotation(kneejointR, 0F, 0F, 0F);
      kneejointR.mirror = false;
      legL = new ModelRenderer(this, 0, 67);
      legL.mirror = true;
      legL.addBox(-2F, 0F, -2F, 4, 8, 4, f);
      legL.setRotationPoint(0F, 0F, 0F);
      legL.setTextureSize(64, 128);
      legL.mirror = true;
      setRotation(legL, 0F, 0F, 0F);
      legL.mirror = false;
      lowerlegL = new ModelRenderer(this, 0, 88);
      lowerlegL.addBox(-0.5F, 4F, -2.5F, 3, 3, 5, f);
      lowerlegL.setRotationPoint(0F, 0F, 0F);
      lowerlegL.setTextureSize(64, 128);
      lowerlegL.mirror = true;
      setRotation(lowerlegL, 0F, 0F, 0F);
      upperlegL = new ModelRenderer(this, 0, 79);
      upperlegL.addBox(-1F, -0.5F, -2.5F, 4, 4, 5, f);
      upperlegL.setRotationPoint(0F, 0F, 0F);
      upperlegL.setTextureSize(64, 128);
      upperlegL.mirror = true;
      setRotation(upperlegL, 0F, 0F, 0F);
      kneejointL = new ModelRenderer(this, 13, 79);
      kneejointL.addBox(1.5F, 3F, -1F, 2, 2, 2);
      kneejointL.setRotationPoint(0F, 0F, 0F);
      kneejointL.setTextureSize(64, 128);
      kneejointL.mirror = true;
      setRotation(kneejointL, 0F, 0F, 0F);
      
      
      this.bipedBody.addChild(pantsbottom);
      this.bipedBody.addChild( pantstop);
      this.bipedBody.addChild( pantsfront);
      this.bipedRightLeg.addChild( legR);
      this.bipedRightLeg.addChild( lowerlegR);
      this.bipedRightLeg.addChild(upperlegR);
      this.bipedRightLeg.addChild(kneejointR);
      this.bipedLeftLeg.addChild( legL);
      this.bipedLeftLeg.addChild(lowerlegL);
      this.bipedLeftLeg.addChild(upperlegL);
      this.bipedLeftLeg.addChild(kneejointL);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
 
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
