// Date: 7/17/2014 3:26:53 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fantastic.renders.models.armor;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGoggles extends ModelBiped
{
  //fields
    ModelRenderer frame6;
    ModelRenderer frame5;
    ModelRenderer frame4;
    ModelRenderer frame1;
    ModelRenderer frame2;
    ModelRenderer frame3;
    ModelRenderer snorklemouthpeice2;
    ModelRenderer snorklemouthpeice1;
    ModelRenderer snorkle1;
    ModelRenderer snorkle3;
    ModelRenderer snorkle2;
    ModelRenderer glass;
    ModelRenderer headstrap;
  
  public ModelGoggles(float f)
  {
	  super(f, 0, 64, 64);
    textureWidth = 64;
    textureHeight = 64;
    

    frame6 = new ModelRenderer(this, 24, 42);
    frame6.addBox(1F, -3F, -5F, 4, 1, 1);
    frame6.setRotationPoint(0F, 0F, 0F);
    frame6.setTextureSize(64, 64);
    frame6.mirror = true;
    setRotation(frame6, 0F, 0F, 0F);
    frame5 = new ModelRenderer(this, 25, 48);
    frame5.addBox(-1F, -4F, -5F, 2, 1, 1);
    frame5.setRotationPoint(0F, 0F, 0F);
    frame5.setTextureSize(64, 64);
    frame5.mirror = true;
    setRotation(frame5, 0F, 0F, 0F);
    frame4 = new ModelRenderer(this, 24, 42);
    frame4.addBox(-5F, -3F, -5F, 4, 1, 1);
    frame4.setRotationPoint(0F, 0F, 0F);
    frame4.setTextureSize(64, 64);
    frame4.mirror = true;
    setRotation(frame4, 0F, 0F, 0F);
    frame1 = new ModelRenderer(this, 19, 42);
    frame1.addBox(-5F, -7F, -5F, 1, 4, 1);
    frame1.setRotationPoint(0F, 0F, 0F);
    frame1.setTextureSize(64, 64);
    frame1.mirror = true;
    setRotation(frame1, 0F, 0F, 0F);
    frame2 = new ModelRenderer(this, 23, 39);
    frame2.addBox(-4F, -7F, -5F, 8, 1, 1);
    frame2.setRotationPoint(0F, 0F, 0F);
    frame2.setTextureSize(64, 64);
    frame2.mirror = true;
    setRotation(frame2, 0F, 0F, 0F);
    frame3 = new ModelRenderer(this, 19, 42);
    frame3.addBox(4F, -7F, -5F, 1, 4, 1);
    frame3.setRotationPoint(0F, 0F, 0F);
    frame3.setTextureSize(64, 64);
    frame3.mirror = true;
    setRotation(frame3, 0F, 0F, 0F);
    snorklemouthpeice2 = new ModelRenderer(this, 26, 32);
    snorklemouthpeice2.addBox(-1F, -2F, -5.5F, 2, 2, 2);
    snorklemouthpeice2.setRotationPoint(0F, 0F, 0F);
    snorklemouthpeice2.setTextureSize(64, 64);
    snorklemouthpeice2.mirror = true;
    setRotation(snorklemouthpeice2, 0F, 0F, 0F);
    snorklemouthpeice1 = new ModelRenderer(this, 25, 36);
    snorklemouthpeice1.addBox(-2F, -2F, -5F, 4, 1, 1);
    snorklemouthpeice1.setRotationPoint(0F, 0F, 0F);
    snorklemouthpeice1.setTextureSize(64, 64);
    snorklemouthpeice1.mirror = true;
    setRotation(snorklemouthpeice1, 0F, 0F, 0F);
    snorkle1 = new ModelRenderer(this, 0, 34);
    snorkle1.addBox(1F, -1F, -5.3F, 4, 1, 1);
    snorkle1.setRotationPoint(0F, 0F, 0F);
    snorkle1.setTextureSize(64, 64);
    snorkle1.mirror = true;
    setRotation(snorkle1, 0F, 0F, 0F);
    snorkle3 = new ModelRenderer(this, 17, 32);
    snorkle3.addBox(4F, -9.5F, -1.5F, 1, 6, 1);
    snorkle3.setRotationPoint(0F, 0F, 0F);
    snorkle3.setTextureSize(64, 64);
    snorkle3.mirror = true;
    setRotation(snorkle3, 0F, 0F, 0F);
    snorkle2 = new ModelRenderer(this, 12, 31);
    snorkle2.addBox(4F, -2F, -4F, 1, 5, 1);
    snorkle2.setRotationPoint(0F, 0F, 0F);
    snorkle2.setTextureSize(64, 64);
    snorkle2.mirror = true;
    setRotation(snorkle2, -0.7853982F, 0F, 0F);
    glass = new ModelRenderer(this, 24, 45);
    glass.addBox(-4F, -6F, -4.6F, 8, 3, 0);
    glass.setRotationPoint(0F, 0F, 0F);
    glass.setTextureSize(64, 64);
    glass.mirror = true;
    setRotation(glass, 0F, 0F, 0F);
    headstrap = new ModelRenderer(this, 0, 21);
    headstrap.addBox(-4.5F, -6F, -4.5F, 9, 1, 9);
    headstrap.setRotationPoint(0F, 0F, 0F);
    headstrap.setTextureSize(64, 64);
    headstrap.mirror = true;
    setRotation(headstrap, 0F, 0F, 0F);
      
      this.bipedHead.addChild(frame1);
      this.bipedHead.addChild(frame2);
      this.bipedHead.addChild(frame3);
      this.bipedHead.addChild(frame4);
      this.bipedHead.addChild(frame5);
      this.bipedHead.addChild(frame6);
      this.bipedHead.addChild(snorklemouthpeice1);
      this.bipedHead.addChild(snorklemouthpeice2);
      this.bipedHead.addChild(snorkle1);
      this.bipedHead.addChild(snorkle2);
      this.bipedHead.addChild(snorkle3);
      this.bipedHead.addChild(glass);
      this.bipedHead.addChild(headstrap);
      this.bipedHeadwear.showModel = false;
  }
  
  public void render(Entity tim, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(tim, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, tim);



  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
