// Date: 7/22/2014 4:10:39 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fantastic.renders.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import fantastic.entities.EntityNurseShark;

public class ModelNurseShark extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Body2;
    ModelRenderer Body3;
    ModelRenderer FinL;
    ModelRenderer FinR;
    ModelRenderer FinTop;
    ModelRenderer FinBack;
    ModelRenderer Head1;
    ModelRenderer Head2;
    ModelRenderer head;
    ModelRenderer lip;
    ModelRenderer body1;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer body4;
    ModelRenderer tail3;
    ModelRenderer tail2;
    ModelRenderer tail1;
    ModelRenderer body5;
    ModelRenderer body6;
    ModelRenderer shape1;
    ModelRenderer shape2;
    ModelRenderer shape3;
    ModelRenderer raw1;
    ModelRenderer raw2;
    ModelRenderer raw3;
    ModelRenderer raw4;
    ModelRenderer raw5;
    ModelRenderer raw6;
    ModelRenderer raw7;
    ModelRenderer raw8;
    ModelRenderer head2;
    ModelRenderer lip2;
    ModelRenderer body12;
    ModelRenderer body22;
    ModelRenderer body32;
    ModelRenderer body42;
    ModelRenderer tail32;
    ModelRenderer tail22;
    ModelRenderer tail12;
    ModelRenderer body52;
    ModelRenderer body62;
    ModelRenderer shape12;
    ModelRenderer shape22;
    ModelRenderer shape32;
    ModelRenderer raw12;
    ModelRenderer raw22;
    ModelRenderer raw32;
    ModelRenderer raw42;
    ModelRenderer raw52;
    ModelRenderer raw62;
    ModelRenderer raw72;
    ModelRenderer raw82;

  
  public ModelNurseShark()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Body = new ModelRenderer(this, 0, 7);
      Body.addBox(-5F, 0F, -4.9F, 10, 16, 5);
      Body.setRotationPoint(0F, 0F, 0F);
      Body.setTextureSize(64, 64);
      Body.mirror = true;
      setRotation(Body, 1.570796F, 0F, 0F);
      Body2 = new ModelRenderer(this, 30, 14);
      Body2.addBox(-4F, 0F, 0F, 8, 4, 9);
      Body2.setRotationPoint(0F, 15.5F, -1F);
      Body2.setTextureSize(64, 64);
      Body2.mirror = true;
      setRotation(Body2, -1.570796F, 0F, 0F);
      Body3 = new ModelRenderer(this, 32, 0);
      Body3.addBox(-2.5F, 0F, 0F, 5, 3, 11);
      Body3.setRotationPoint(0F, 0.5F, 8F);
      Body3.setTextureSize(64, 64);
      Body3.mirror = true;
      setRotation(Body3, 0F, 0F, 0F);
      FinL = new ModelRenderer(this, 28, 27);
      FinL.addBox(3.5F, 0F, 0F, 7, 1, 11);
      FinL.setRotationPoint(0.3F, 19F, 7.7F);
      FinL.setTextureSize(64, 64);
      FinL.mirror = true;
      setRotation(FinL, -0.2443461F, 1.117011F, 0F);
      FinR = new ModelRenderer(this, 28, 27);
      FinR.addBox(-3.5F, 0F, 0F, 7, 1, 11);
      FinR.setRotationPoint(-3.2F, 18.9F, 1.3F);
      FinR.setTextureSize(64, 64);
      FinR.mirror = true;
      setRotation(FinR, -0.2443461F, -1.117011F, 0F);
      FinTop = new ModelRenderer(this, 0, 28);
      FinTop.addBox(-0.5F, 1F, 0.7F, 1, 7, 7);
      FinTop.setRotationPoint(0F, 0F, 0F);
      FinTop.setTextureSize(64, 64);
      FinTop.mirror = true;
      setRotation(FinTop, 0.9773844F, 0F, 0F);
      FinBack = new ModelRenderer(this, 0, 42);
      FinBack.addBox(-1F, 7F, 1F, 2, 6, 12);
      FinBack.setRotationPoint(0F, 0F, 0F);
      FinBack.setTextureSize(64, 64);
      FinBack.mirror = true;
      setRotation(FinBack, 1.064651F, 0F, 0F);
      Head1 = new ModelRenderer(this, 0, 0);
      Head1.addBox(-5F, -0.1F, -3.9F, 10, 2, 4);
      Head1.setRotationPoint(0F, 0F, 0F);
      Head1.setTextureSize(64, 64);
      Head1.mirror = true;
      setRotation(Head1, 0.5340708F, 0F, 0F);
      Head2 = new ModelRenderer(this, 18, 0);
      Head2.addBox(-5F, 1.9F, -3.4F, 10, 3, 4);
      Head2.setRotationPoint(0F, 16F, -7F);
      Head2.setTextureSize(64, 64);
      Head2.mirror = true;
      setRotation(Head2, 0F, 0F, 0F);
      
      
      head = new ModelRenderer(this, 31, 42);
      head.addBox(6F, 0F, 0F, 1, 4, 4);
      head.setRotationPoint(0F, 10F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, -0.7853982F, 0F, 0F);
      lip = new ModelRenderer(this, 37, 40);
      lip.addBox(6F, 4F, 1F, 1, 1, 3);
      lip.setRotationPoint(0F, 0F, 0F);
      lip.setTextureSize(64, 64);
      lip.mirror = true;
      setRotation(lip, -0F, 0F, 0F);
      body1 = new ModelRenderer(this, 43, 40);
      body1.addBox(6F, -2F, 1F, 1, 2, 8);
      body1.setRotationPoint(0F, 0F, 0F);
      body1.setTextureSize(64, 64);
      body1.mirror = true;
      setRotation(body1, -0F, 0F, 0F);
      body2 = new ModelRenderer(this, 29, 52);
      body2.addBox(6F, -5F, 4F, 1, 3, 5);
      body2.setRotationPoint(0F, 0F, 0F);
      body2.setTextureSize(64, 64);
      body2.mirror = true;
      setRotation(body2, 0F, 0F, 0F);
      body3 = new ModelRenderer(this, 43, 44);
      body3.addBox(6F, -6F, 6F, 1, 1, 3);
      body3.setRotationPoint(0F, 0F, 0F);
      body3.setTextureSize(64, 64);
      body3.mirror = true;
      setRotation(body3, 0F, 0F, 0F);
      body4 = new ModelRenderer(this, 45, 50);
      body4.addBox(6F, -9F, 9F, 1, 8, 1);
      body4.setRotationPoint(0F, 0F, 0F);
      body4.setTextureSize(64, 64);
      body4.mirror = true;
      setRotation(body4, 0F, 0F, 0F);
      tail3 = new ModelRenderer(this, 49, 50);
      tail3.addBox(6F, -7F, 10F, 1, 3, 3);
      tail3.setRotationPoint(0F, 0F, 0F);
      tail3.setTextureSize(64, 64);
      tail3.mirror = true;
      setRotation(tail3, 0F, 0F, 0F);
      tail2 = new ModelRenderer(this, 53, 44);
      tail2.addBox(6F, -8F, 11F, 1, 1, 1);
      tail2.setRotationPoint(0F, 0F, 0F);
      tail2.setTextureSize(64, 64);
      tail2.mirror = true;
      setRotation(tail2, 0F, 0F, 0F);
      tail1 = new ModelRenderer(this, 29, 50);
      tail1.addBox(6F, -9F, 10F, 1, 2, 1);
      tail1.setRotationPoint(0F, 0F, 0F);
      tail1.setTextureSize(64, 64);
      tail1.mirror = true;
      setRotation(tail1, 0F, 0F, 0F);
      body5 = new ModelRenderer(this, 54, 41);
      body5.addBox(6F, 0F, 6F, 1, 1, 2);
      body5.setRotationPoint(0F, 0F, 0F);
      body5.setTextureSize(64, 64);
      body5.mirror = true;
      setRotation(body5, 0F, 0F, 0F);
      body6 = new ModelRenderer(this, 46, 41);
      body6.addBox(6F, 1F, 6F, 1, 1, 1);
      body6.setRotationPoint(0F, 0F, 0F);
      body6.setTextureSize(64, 64);
      body6.mirror = true;
      setRotation(body6, 0F, 0F, 0F);
      shape1 = new ModelRenderer(this, 39, 50);
      shape1.addBox(6F, -3F, 2F, 1, 1, 1);
      shape1.setRotationPoint(0F, 0F, 0F);
      shape1.setTextureSize(64, 64);
      shape1.mirror = true;
      setRotation(shape1, 0F, 0F, 0F);
      shape2 = new ModelRenderer(this, 38, 53);
      shape2.addBox(6F, -4F, 3F, 1, 2, 1);
      shape2.setRotationPoint(0F, 0F, 0F);
      shape2.setTextureSize(64, 64);
      shape2.mirror = true;
      setRotation(shape2, 0F, 0F, 0F);
      shape3 = new ModelRenderer(this, 55, 55);
      shape3.addBox(6F, 0F, 4F, 1, 3, 2);
      shape3.setRotationPoint(0F, 0F, 0F);
      shape3.setTextureSize(64, 64);
      shape3.mirror = true;
      setRotation(shape3, 0F, 0F, 0F);
      raw1 = new ModelRenderer(this, 41, 59);
      raw1.addBox(6F, -1F, 9F, 1, 1, 1);
      raw1.setRotationPoint(0F, 0F, 0F);
      raw1.setTextureSize(64, 64);
      raw1.mirror = true;
      setRotation(raw1, 0F, 0F, 0F);
      raw2 = new ModelRenderer(this, 41, 59);
      raw2.addBox(6F, 0F, 8F, 1, 1, 1);
      raw2.setRotationPoint(0F, 0F, 0F);
      raw2.setTextureSize(64, 64);
      raw2.mirror = true;
      setRotation(raw2, 0F, 0F, 0F);
      raw3 = new ModelRenderer(this, 41, 59);
      raw3.addBox(6F, 1F, 7F, 1, 1, 1);
      raw3.setRotationPoint(0F, 0F, 0F);
      raw3.setTextureSize(64, 64);
      raw3.mirror = true;
      setRotation(raw3, 0F, 0F, 0F);
      raw4 = new ModelRenderer(this, 41, 59);
      raw4.addBox(6F, 2F, 6F, 1, 1, 1);
      raw4.setRotationPoint(0F, 0F, 0F);
      raw4.setTextureSize(64, 64);
      raw4.mirror = true;
      setRotation(raw4, 0F, 0F, 0F);
      raw5 = new ModelRenderer(this, 48, 58);
      raw5.addBox(6F, 3F, 4F, 1, 1, 2);
      raw5.setRotationPoint(0F, 0F, 0F);
      raw5.setTextureSize(64, 64);
      raw5.mirror = true;
      setRotation(raw5, 0F, 0F, 0F);
      raw6 = new ModelRenderer(this, 60, 45);
      raw6.addBox(6F, -4F, 2F, 1, 1, 1);
      raw6.setRotationPoint(0F, 0F, 0F);
      raw6.setTextureSize(64, 64);
      raw6.mirror = true;
      setRotation(raw6, 0F, 0F, 0F);
      raw7 = new ModelRenderer(this, 58, 51);
      raw7.addBox(6F, -5F, 2F, 1, 1, 2);
      raw7.setRotationPoint(0F, 0F, 0F);
      raw7.setTextureSize(64, 64);
      raw7.mirror = true;
      setRotation(raw7, 0F, 0F, 0F);
      raw8 = new ModelRenderer(this, 58, 51);
      raw8.addBox(6F, -6F, 3F, 1, 1, 2);
      raw8.setRotationPoint(0F, 0F, 0F);
      raw8.setTextureSize(64, 64);
      raw8.mirror = true;
      setRotation(raw8, 0F, 0F, 0F);
      
      head2 = new ModelRenderer(this, 31, 42);
      head2.addBox(-7F, 0F, 0F, 1, 4, 4);
      head2.setRotationPoint(0F, 10F, 0F);
      head2.setTextureSize(64, 64);
      head2.mirror = true;
      setRotation(head2, -0.7853982F, 0F, 0F);
      lip2 = new ModelRenderer(this, 37, 40);
      lip2.addBox(-7F, 4F, 1F, 1, 1, 3);
      lip2.setRotationPoint(0F, 0F, 0F);
      lip2.setTextureSize(64, 64);
      lip2.mirror = true;
      setRotation(lip2, 0F, 0F, 0F);
      body12 = new ModelRenderer(this, 43, 40);
      body12.addBox(-7F, -2F, 1F, 1, 2, 8);
      body12.setRotationPoint(0F, 0F, 0F);
      body12.setTextureSize(64, 64);
      body12.mirror = true;
      setRotation(body12, 0F, 0F, 0F);
      body22 = new ModelRenderer(this, 29, 52);
      body22.addBox(-7F, -5F, 4F, 1, 3, 5);
      body22.setRotationPoint(0F, 0F, 0F);
      body22.setTextureSize(64, 64);
      body22.mirror = true;
      setRotation(body22, 0F, 0F, 0F);
      body32 = new ModelRenderer(this, 43, 44);
      body32.addBox(-7F, -6F, 6F, 1, 1, 3);
      body32.setRotationPoint(0F, 0F, 0F);
      body32.setTextureSize(64, 64);
      body32.mirror = true;
      setRotation(body32, 0F, 0F, 0F);
      body42 = new ModelRenderer(this, 45, 50);
      body42.addBox(-7F, -9F, 9F, 1, 8, 1);
      body42.setRotationPoint(0F, 0F, 0F);
      body42.setTextureSize(64, 64);
      body42.mirror = true;
      setRotation(body42, 0F, 0F, 0F);
      tail32 = new ModelRenderer(this, 49, 50);
      tail32.addBox(-7F, -7F, 10F, 1, 3, 3);
      tail32.setRotationPoint(0F, 0F, 0F);
      tail32.setTextureSize(64, 64);
      tail32.mirror = true;
      setRotation(tail32, 0F, 0F, 0F);
      tail22 = new ModelRenderer(this, 53, 44);
      tail22.addBox(-7F, -8F, 11F, 1, 1, 1);
      tail22.setRotationPoint(0F, 0F, 0F);
      tail22.setTextureSize(64, 64);
      tail22.mirror = true;
      setRotation(tail22, 0F, 0F, 0F);
      tail12 = new ModelRenderer(this, 29, 50);
      tail12.addBox(-7F, -9F, 10F, 1, 2, 1);
      tail12.setRotationPoint(0F, 0F, 0F);
      tail12.setTextureSize(64, 64);
      tail12.mirror = true;
      setRotation(tail12, 0F, 0F, 0F);
      body52 = new ModelRenderer(this, 54, 41);
      body52.addBox(-7F, 0F, 6F, 1, 1, 2);
      body52.setRotationPoint(0F, 0F, 0F);
      body52.setTextureSize(64, 64);
      body52.mirror = true;
      setRotation(body52, 0F, 0F, 0F);
      body62 = new ModelRenderer(this, 46, 41);
      body62.addBox(-7F, 1F, 6F, 1, 1, 1);
      body62.setRotationPoint(0F, 0F, 0F);
      body62.setTextureSize(64, 64);
      body62.mirror = true;
      setRotation(body62, 0F, 0F, 0F);
      shape12 = new ModelRenderer(this, 39, 50);
      shape12.addBox(-7F, -3F, 2F, 1, 1, 1);
      shape12.setRotationPoint(0F, 0F, 0F);
      shape12.setTextureSize(64, 64);
      shape12.mirror = true;
      setRotation(shape12, 0F, 0F, 0F);
      shape22 = new ModelRenderer(this, 38, 53);
      shape22.addBox(-7F, -4F, 3F, 1, 2, 1);
      shape22.setRotationPoint(0F, 0F, 0F);
      shape22.setTextureSize(64, 64);
      shape22.mirror = true;
      setRotation(shape22, 0F, 0F, 0F);
      shape32 = new ModelRenderer(this, 55, 55);
      shape32.addBox(-7F, 0F, 4F, 1, 3, 2);
      shape32.setRotationPoint(0F, 0F, 0F);
      shape32.setTextureSize(64, 64);
      shape32.mirror = true;
      setRotation(shape32, 0F, 0F, 0F);
      raw12 = new ModelRenderer(this, 41, 59);
      raw12.addBox(-7F, -1F, 9F, 1, 1, 1);
      raw12.setRotationPoint(0F, 0F, 0F);
      raw12.setTextureSize(64, 64);
      raw12.mirror = true;
      setRotation(raw12, 0F, 0F, 0F);
      raw22 = new ModelRenderer(this, 41, 59);
      raw22.addBox(-7F, 0F, 8F, 1, 1, 1);
      raw22.setRotationPoint(0F, 0F, 0F);
      raw22.setTextureSize(64, 64);
      raw22.mirror = true;
      setRotation(raw22, 0F, 0F, 0F);
      raw32 = new ModelRenderer(this, 41, 59);
      raw32.addBox(-7F, 1F, 7F, 1, 1, 1);
      raw32.setRotationPoint(0F, 0F, 0F);
      raw32.setTextureSize(64, 64);
      raw32.mirror = true;
      setRotation(raw32, 0F, 0F, 0F);
      raw42 = new ModelRenderer(this, 41, 59);
      raw42.addBox(-7F, 2F, 6F, 1, 1, 1);
      raw42.setRotationPoint(0F, 0F, 0F);
      raw42.setTextureSize(64, 64);
      raw42.mirror = true;
      setRotation(raw42, 0F, 0F, 0F);
      raw52 = new ModelRenderer(this, 48, 58);
      raw52.addBox(-7F, 3F, 4F, 1, 1, 2);
      raw52.setRotationPoint(0F, 0F, 0F);
      raw52.setTextureSize(64, 64);
      raw52.mirror = true;
      setRotation(raw52, 0F, 0F, 0F);
      raw62 = new ModelRenderer(this, 60, 45);
      raw62.addBox(-7F, -4F, 2F, 1, 1, 1);
      raw62.setRotationPoint(0F, 0F, 0F);
      raw62.setTextureSize(64, 64);
      raw62.mirror = true;
      setRotation(raw62, 0F, 0F, 0F);
      raw72 = new ModelRenderer(this, 58, 51);
      raw72.addBox(-7F, -5F, 2F, 1, 1, 2);
      raw72.setRotationPoint(0F, 0F, 0F);
      raw72.setTextureSize(64, 64);
      raw72.mirror = true;
      setRotation(raw72, 0F, 0F, 0F);
      raw82 = new ModelRenderer(this, 58, 51);
      raw82.addBox(-7F, -6F, 3F, 1, 1, 2);
      raw82.setRotationPoint(0F, 0F, 0F);
      raw82.setTextureSize(64, 64);
      raw82.mirror = true;
      setRotation(raw82, 0F, 0F, 0F);
      
      Head2.addChild(Head1);
      Head2.addChild(Body);
      Body.addChild(Body2);
      Body2.addChild(Body3);
      Body3.addChild(FinBack);
      Body2.addChild(FinTop);
      
      head.addChild(lip);
      lip.addChild(body1);
      body1.addChild(body2);
      body2.addChild(body3);
      body3.addChild(body4);
      body4.addChild(body5);
      body5.addChild(body6);
      body2.addChild(raw1);
      raw1.addChild(raw2);
      raw2.addChild(raw3);
      raw3.addChild(raw4);
      raw4.addChild(raw5);
      raw5.addChild(raw6);
      raw6.addChild(raw7);
      raw7.addChild(raw8);
      body1.addChild(shape1);
      body2.addChild(shape2);
      body3.addChild(shape3);
      body6.addChild(tail1);
      tail1.addChild(tail2);
      tail2.addChild(tail3);
      
      head2.addChild(lip2);
      lip2.addChild(body12);
      body12.addChild(body22);
      body22.addChild(body32);
      body32.addChild(body42);
      body42.addChild(body52);
      body52.addChild(body62);
      body22.addChild(raw12);
      raw12.addChild(raw22);
      raw22.addChild(raw32);
      raw32.addChild(raw42);
      raw42.addChild(raw52);
      raw52.addChild(raw62);
      raw62.addChild(raw72);
      raw72.addChild(raw82);
      body12.addChild(shape12);
      body22.addChild(shape22);
      body32.addChild(shape32);
      body62.addChild(tail12);
      tail12.addChild(tail22);
      tail22.addChild(tail32);
      

  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
   
    Head2.render(f5);
    FinL.render(f5);
    FinR.render(f5);
    if(((EntityNurseShark)entity).getFish() > 0)
    {
    	head.render(f5);
//    	lip.render(f5);
//    	body1.render(f5);
//    	body2.render(f5);
//    	body3.render(f5);
//    	body4.render(f5);
//    	tail3.render(f5);
//    	tail2.render(f5);
//    	tail1.render(f5);
//    	body5.render(f5);
//    	body6.render(f5);
//    	shape1.render(f5);
//    	shape2.render(f5);
//    	shape3.render(f5);
//    	raw1.render(f5);
//    	raw2.render(f5);
//    	raw3.render(f5);
//    	raw4.render(f5);
//    	raw5.render(f5);
//    	raw6.render(f5);
//    	raw7.render(f5);
//    	raw8.render(f5);
    }
    if(((EntityNurseShark)entity).getFish() > 1)
    {
    	head2.render(f5);
//    	lip2.render(f5);
//    	body12.render(f5);
//    	body22.render(f5);
//    	body32.render(f5);
//    	body42.render(f5);
//    	tail32.render(f5);
//    	tail22.render(f5);
//    	tail12.render(f5);
//    	body52.render(f5);
//    	body62.render(f5);
//    	shape12.render(f5);
//    	shape22.render(f5);
//    	shape32.render(f5);
//    	raw12.render(f5);
//    	raw22.render(f5);
//    	raw32.render(f5);
//    	raw42.render(f5);
//    	raw52.render(f5);
//    	raw62.render(f5);
//    	raw72.render(f5);
//    	raw82.render(f5);
    }
   
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    

    this.Head2.rotateAngleY = (float)(0.1*(MathHelper.cos(f2 * 0.2F)) ) + 0.05F;
    this.Body2.rotateAngleZ = (float)(0.15*(MathHelper.cos(f2 * 0.2F - (float)(Math.PI/2) )) );
    this.Body3.rotateAngleY = (float)(0.2*(MathHelper.cos(f2 * 0.2F)) );
    if(((EntityNurseShark)entity).getIsOutOfWater() == 0)
    {
    	this.FinL.rotateAngleZ = -(float)(0.2*(MathHelper.cos(f2 * 0.6F)) );
    	this.FinR.rotateAngleZ = -(float)(0.2*(MathHelper.sin(f2 * 0.6F)) );
    }

	this.FinL.rotateAngleY = (float)(0.1*(MathHelper.cos(f2 * 0.2F)) ) + 1.117011F;
	this.FinR.rotateAngleY = (float)(0.1*(MathHelper.cos(f2 * 0.2F)) ) - 1.117011F;
	
	
	
	

    this.head.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body1.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body2.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body3.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body4.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body5.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body6.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    tail1.rotateAngleY = (float)(0.006*(MathHelper.cos(f2 * 0.2F)) )  ;
    tail2.rotateAngleY = (float)(0.006*(MathHelper.cos(f2 * 0.2F)) )  ;
    tail3.rotateAngleY = (float)(0.006*(MathHelper.cos(f2 * 0.2F)) )  ;
    

    this.head.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body1.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body2.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body3.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body4.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body5.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body6.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    tail1.rotateAngleZ = (float)(0.006*(MathHelper.cos(f2 * 0.2F)) )  ;
    tail2.rotateAngleZ = (float)(0.006*(MathHelper.cos(f2 * 0.2F)) )  ;
    tail3.rotateAngleZ = (float)(0.006*(MathHelper.cos(f2 * 0.2F)) )  ;
    
    
    this.head2.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body12.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body22.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body32.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body42.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body52.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body62.rotateAngleY = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    tail12.rotateAngleY = (float)(0.006*(MathHelper.cos(f2 * 0.2F)) )  ;
    tail22.rotateAngleY = (float)(0.006*(MathHelper.cos(f2 * 0.2F)) )  ;
    tail32.rotateAngleY = (float)(0.006*(MathHelper.cos(f2 * 0.2F)) )  ;
    

    this.head2.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body12.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body22.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body32.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body42.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body52.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    body62.rotateAngleZ = (float)(0.02*(MathHelper.cos(f2 * 0.2F)) )  ;
    tail12.rotateAngleZ = (float)(0.006*(MathHelper.cos(f2 * 0.2F)) )  ;
    tail22.rotateAngleZ = (float)(0.006*(MathHelper.cos(f2 * 0.2F)) )  ;
    tail32.rotateAngleZ = (float)(0.006*(MathHelper.cos(f2 * 0.2F)) )  ;
    
  }

}
